const $ = (selector) => document.querySelector(selector);
const normalizeWhatsappNumber = (value) => String(value || "").replace(/\D/g, "");
let products = [];
let catalogConfig = { whatsappNumber: "" };
const fallbackProducts = [
  {id:"latitude-7450",name:"Latitude 7450",brand:"Dell",category:"Laptops",model:"LAT7450-ULTRA7",condition:"New",tag:"Business laptop",specs:["Intel Core Ultra 7","32GB RAM","1TB SSD"],image:"https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=85",description:"A secure, capable laptop for modern business teams."},
  {id:"thinkvision-p34w",name:"ThinkVision P34w-20",brand:"Lenovo",category:"Monitors",model:"62CCRAT3UK",condition:"New",tag:"Monitor",specs:["34in WQHD","USB-C docking","IPS panel"],image:"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=85",description:"An ultra-wide display with a clean, productive workspace."},
  {id:"prodesk-400",name:"ProDesk 400 G9",brand:"HP",category:"Desktop Computers",model:"6U3Z2EA",condition:"New",tag:"Desktop",specs:["Intel Core i7","16GB RAM","512GB SSD"],image:"https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=900&q=85",description:"Reliable desktop performance for everyday business work."}
];
const categoryIcons = {Laptops:"▱",Monitors:"▣","Desktop Computers":"▤",Mouse:"◉",Networking:"⌁",Keyboards:"⌨",Printers:"▤",Accessories:"✦"};
let activeCategory = "All";
const productCard = p => `<article class="product-card"><div class="product-image" onclick="openProduct('${p.id}')"><img loading="lazy" src="${p.image}" alt="${p.name}"/><span class="tag">${p.tag}</span><button class="wish" aria-label="Save ${p.name}" onclick="event.stopPropagation();this.textContent=this.textContent==='♡'?'♥':'♡'">♡</button></div><div class="product-meta"><p>${p.brand} · ${p.category}</p><h3>${p.name}</h3><div class="small-spec">${p.specs.slice(0,2).join(' · ')}</div><button class="request" onclick="requestPrice('${p.id}')">Request price ↗</button></div></article>`;
function renderProducts(){const term=$('#productSearch').value.toLowerCase();const list=products.filter(p=>{const search=Object.values(p).flat().join(' ').toLowerCase();return (activeCategory==='All'||p.category===activeCategory)&&search.includes(term)});$('#catalogGrid').innerHTML=list.map(productCard).join('');$('#emptyState').hidden=!!list.length}
function renderCategories(){const cats=[...new Set(products.map(p=>p.category))];$('#categoryGrid').innerHTML=cats.map(c=>{const count=products.filter(p=>p.category===c).length;return `<button class="category ${activeCategory===c?'active':''}" onclick="selectCategory('${c}')"><span class="category-icon">${categoryIcons[c]||'◇'}</span><span class="category-copy"><strong>${c}</strong><small>${count} product${count===1?'':'s'}</small></span><span class="category-arrow">→</span></button>`}).join('');$('#filterChips').innerHTML=['All',...cats].map(c=>`<button class="chip ${activeCategory===c?'active':''}" onclick="selectCategory('${c}')">${c}</button>`).join('')}
function selectCategory(category){activeCategory=category;renderCategories();renderProducts();location.hash='products'}
function requestPrice(id){const p=products.find(x=>x.id===id);const url=location.href.split('#')[0]+'#product-'+p.id;const msg=`Hello,%0A%0AI am interested in this product.%0A%0AProduct Name: ${p.name}%0AModel Number: ${p.model}%0AProduct URL: ${url}%0A%0APlease send me the latest price and availability.%0A%0AThank you.`;window.open(`https://wa.me/${catalogConfig.whatsappNumber}?text=${msg}`,'_blank','noopener')}
function openProduct(id){const p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-body"><img src="${p.image}" alt="${p.name}"/><div class="modal-info"><p class="eyebrow">${p.brand.toUpperCase()} · ${p.category.toUpperCase()}</p><h2>${p.name}</h2><p>${p.description}</p><ul class="spec-list">${p.specs.map(s=>`<li>${s}</li>`).join('')}<li>Model: ${p.model}</li><li>Condition: ${p.condition}</li></ul><a class="whatsapp" href="#" onclick="requestPrice('${p.id}');return false">Request price on WhatsApp ↗</a></div></div>`;$('#productModal').showModal()}
function renderSearch(term){const hits=products.filter(p=>Object.values(p).flat().join(' ').toLowerCase().includes(term.toLowerCase())).slice(0,6);$('#searchResults').innerHTML=term?hits.map(p=>`<div class="search-result" onclick="openProduct('${p.id}');$('#searchOverlay').classList.remove('active')"><small>${p.brand} · ${p.category}</small><strong>${p.name}</strong></div>`).join(''):'<p class="search-hint">Start typing to search all products.</p>'}
function initialise(){
  document.querySelectorAll('a[href^="https://wa.me/"]').forEach(link=>link.href=`https://wa.me/${catalogConfig.whatsappNumber}`);
  $('#featuredGrid').innerHTML=products.slice(0,4).map(productCard).join('');renderCategories();renderProducts();$('#year').textContent=new Date().getFullYear();
$('#productSearch').addEventListener('input',renderProducts);$('.search-toggle').onclick=()=>{$('#searchOverlay').classList.add('active');$('#overlaySearch').focus()};$('.close-search').onclick=()=>$('#searchOverlay').classList.remove('active');$('#overlaySearch').addEventListener('input',e=>renderSearch(e.target.value));$('.modal-close').onclick=()=>$('#productModal').close();$('#filterButton').onclick=()=>$('#productSearch').focus();$('#nextProduct').onclick=()=>$('#featuredGrid').scrollBy({left:300,behavior:'smooth'});$('#previousProduct').onclick=()=>$('#featuredGrid').scrollBy({left:-300,behavior:'smooth'});
  $('.mobile-search').onclick=()=>{$('#searchOverlay').classList.add('active');$('#overlaySearch').focus()};
}
fetch('data/products.json').then(response=>{if(!response.ok)throw new Error('Catalog data unavailable');return response.json()}).then(data=>{products=data.products||[];catalogConfig.whatsappNumber=normalizeWhatsappNumber(data.whatsappNumber);initialise()}).catch(()=>{products=fallbackProducts;catalogConfig.whatsappNumber=normalizeWhatsappNumber("+971 585008564");initialise()});
$('.theme-toggle').onclick=()=>{document.body.classList.toggle('dark');$('.theme-toggle').textContent=document.body.classList.contains('dark')?'☼':'◐'};
